def obfuscated = rootProject.targetVersion.java == 21
apply plugin: obfuscated ? "net.fabricmc.fabric-loom-remap" : "net.fabricmc.fabric-loom"
apply from: rootProject.file("gradle/minecraft-module.gradle")
dependencies {
    minecraft "com.mojang:minecraft:${rootProject.minecraftVersion}"
    if (obfuscated) {
        mappings loom.officialMojangMappings()
        modImplementation "net.fabricmc:fabric-loader:0.19.5"
    } else {
        implementation "net.fabricmc:fabric-loader:0.19.5"
    }
}
if (obfuscated) {
    tasks.named("remapJar") { archiveClassifier = "" }
}
