plugins {
    id "java"
}

def modVersion = version.toString()

base {
    archivesName = "SimpleKillCommand-Forge"
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

dependencies {
    compileOnly "net.minecraftforge:forge:1.21.11-61.1.8:universal"
    compileOnly "net.minecraftforge:javafmllanguage:1.21.11-61.1.8"
    compileOnly "net.minecraftforge:eventbus:7.0.1"
    compileOnly "com.mojang:brigadier:1.3.10"
}

sourceSets {
    main {
        java.srcDir(project(":common").file("src/main/java"))
    }
}

processResources {
    filteringCharset = "UTF-8"
    inputs.property("version", modVersion)
    filesMatching("META-INF/mods.toml") {
        expand(version: modVersion)
    }
}

jar {
}
